version: '3'

services:
  test:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: artem
      POSTGRES_PASSWORD: '12345'
    volumes:
      - ./db:/docker-entrypoint-initdb.d:rw

